CC = gcc
SRC = main.c defination.c authentication.c
OBJ = $(SRC:.c=.o)
OUT = fee_system

all: $(OUT)

$(OUT): $(OBJ)
	$(CC) $(OBJ) -o $(OUT)

%.o: %.c
	$(CC) -c $< -o $@

clean:
	rm -f *.o $(OUT)
cd "/Users/namangarg/collage feee/" && gcc MAKEFILE.C -o MAKEFILE && "/Users/namangarg/collage feee/"MAKEFILE
cd "/Users/namangarg/collage feee/" && gcc MAKEFILE.C -o MAKEFILE && "/Users/namangarg/collage feee/"MAKEFILE
cd "/Users/namangarg/collage feee/" && gcc MAKEFILE.C -o MAKEFILE && "/Users/namangarg/collage feee/"MAKEFILE
make
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main
cd "/Users/namangarg/collage feee/" && gcc main.c -o main && "/Users/namangarg/collage feee/"main

